In [4]:
import numpy as np
import pandas as pd

from sklearn.metrics import mean_squared_error, r2_score
from sklearn import linear_model
from sklearn.metrics import accuracy_score 
from sklearn.model_selection import train_test_split

In [5]:
df = pd.read_csv("houseprice.csv")

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6394 entries, 0 to 6393
Data columns (total 21 columns):
id               6394 non-null int64
date             6394 non-null object
price            6394 non-null float64
bedrooms         6394 non-null int64
bathrooms        6394 non-null float64
sqft_living      6394 non-null int64
sqft_lot         6394 non-null int64
floors           6394 non-null float64
waterfront       6394 non-null int64
view             6394 non-null int64
condition        6394 non-null int64
grade            6394 non-null int64
sqft_above       6394 non-null int64
sqft_basement    6393 non-null float64
yr_built         6393 non-null float64
yr_renovated     6393 non-null float64
zipcode          6393 non-null float64
lat              6393 non-null float64
long             6393 non-null float64
sqft_living15    6393 non-null float64
sqft_lot15       6393 non-null float64
dtypes: float64(11), int64(9), object(1)
memory usage: 1.0+ MB

In [7]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0.0,1955.0,0.0,98178.0,47.5112,-122.257,1340.0,5650.0
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400.0,1951.0,1991.0,98125.0,47.7210,-122.319,1690.0,7639.0
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0.0,1933.0,0.0,98028.0,47.7379,-122.233,2720.0,8062.0
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910.0,1965.0,0.0,98136.0,47.5208,-122.393,1360.0,5000.0
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0.0,1987.0,0.0,98074.0,47.6168,-122.045,1800.0,7503.0

In [8]:
conv_dates = [1 if values == 2014 else 0 for values in df.date ]
df['date'] = conv_dates

In [9]:
df = df.drop(['id', 'lat', 'long'], axis=1)

In [10]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,sqft_living15,sqft_lot15
0,0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0.0,1955.0,0.0,98178.0,1340.0,5650.0
1,0,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400.0,1951.0,1991.0,98125.0,1690.0,7639.0
2,0,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0.0,1933.0,0.0,98028.0,2720.0,8062.0
3,0,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910.0,1965.0,0.0,98136.0,1360.0,5000.0
4,0,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0.0,1987.0,0.0,98074.0,1800.0,7503.0

In [27]:
target = df['price'].values
features = df.drop(['price'],axis=1).values

In [28]:
X_train , X_test , y_train , y_test = train_test_split(features , target , test_size = 0.3,random_state =42)

In [29]:
model = linear_model.LinearRegression()

In [30]:
model.fit(X_train, y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [31]:
predict = model.predict(X_test)

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [32]:
accuracy = model.score(X_test, y_test)
mse = mean_squared_error(y_test, predict)
r2 = r2_score(y_test, predict)

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [ ]:
print("Accuracy Score: %f\nMean Squared Error: %.02f\nr2 Score: %f"%(accuracy, mse, r2))